"""Common settings for Deep Composer
"""
__author__ = 'epnichols'


# Metric grid
BEATS_PER_MEASURE = 16  # 16th note quantization

# Bit vector definition.
NUMBER_MELODY_PITCHES = 36
NUMBER_HARMONY_PITCHES = 12
NUMBER_CONTINUATION_FLAGS = 1
NUMBER_METRIC_FLAGS = 5

# Computed bit vector ranges
MELODY_INDICES_RANGE = (0, NUMBER_MELODY_PITCHES)  # exclusive top range
HARMONY_INDICES_RANGE = (MELODY_INDICES_RANGE[1], MELODY_INDICES_RANGE[1] + NUMBER_HARMONY_PITCHES)
CONTINUATION_FLAG_RANGE = (HARMONY_INDICES_RANGE[1], HARMONY_INDICES_RANGE[1] + NUMBER_CONTINUATION_FLAGS)
METRIC_FLAGS_RANGE = (CONTINUATION_FLAG_RANGE[1], CONTINUATION_FLAG_RANGE[1] + NUMBER_METRIC_FLAGS)

# LSTM Parameters
DEFAULT_WINDOW_SIZE = 3  # number of frames per training window
